# $schema: https://json.schemastore.org/github-action
name: 'Create Log4j changelog entries from Dependabot PRs'
description: |
  This action creates changelog entries for Dependabot commits.
  For each updated dependency a new changelog entry file is created in the `src/changelog` directory.
inputs:
  token:
    description: 'GitHub token'
    required: true
    default: '${{ github.token }}'
  sha:
    description: 'SHA1 of the commit to use'
    required: true
    default: '${{ github.sha }}'
  changelog-path:
    description: 'Directory where the changelog entries are created'
    required: true
    default: 'src/changelog'
outputs:
  dependency-count:
    description: 'Number of changelog entries created'
  pull-request-html-url:
    description: 'HTML URL of the pull request'
  pull-request-number:
    description: 'Number of the pull request'
runs:
  using: 'node20'
  main: 'dist/index.js'